//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Challenge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Challenge()
        {
            this.UserDati = new HashSet<UserDati>();
        }
    
        public int Timu_id { get; set; }
        public string Timu { get; set; }
        public string AnswerA { get; set; }
        public string AnswerB { get; set; }
        public Nullable<int> ChallengeK_id { get; set; }
    
        public virtual ChallengeK ChallengeK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserDati> UserDati { get; set; }
    }
}
