//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ci()
        {
            this.CiComment = new HashSet<CiComment>();
        }
    
        public int Ci_id { get; set; }
        public string CiTitle { get; set; }
        public string CiContent { get; set; }
        public string CiFanyi { get; set; }
        public string CiShangxi { get; set; }
        public string Cibeijing { get; set; }
        public string CiYuying { get; set; }
        public Nullable<int> Author_id { get; set; }
        public Nullable<int> Time_id { get; set; }
        public Nullable<int> Cipai_id { get; set; }
        public string CiImage { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Time Time { get; set; }
        public virtual CiPai CiPai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CiComment> CiComment { get; set; }
    }
}
