//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageReply_id { get; set; }
        public string Users_id { get; set; }
        public string MessageReplyContent { get; set; }
        public Nullable<System.DateTime> ReplyTime { get; set; }
        public string MessageReReply_id { get; set; }
        public string host_id { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        public virtual UserInfo UserInfo1 { get; set; }
        public virtual UserInfo UserInfo2 { get; set; }
    }
}
