//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shi()
        {
            this.ShiComment = new HashSet<ShiComment>();
        }
    
        public int Shi_id { get; set; }
        public string ShiTitle { get; set; }
        public string ShiContent { get; set; }
        public string ShiFanyi { get; set; }
        public string ShiShangxi { get; set; }
        public string Shibeijing { get; set; }
        public string ShiYuying { get; set; }
        public Nullable<int> Author_id { get; set; }
        public Nullable<int> Time_id { get; set; }
        public Nullable<int> ShiType_id { get; set; }
        public string ShiImage { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string ShiJieShao { get; set; }
        public string Shizhixiang { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual ShiType ShiType { get; set; }
        public virtual Time Time { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShiComment> ShiComment { get; set; }
    }
}
