//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiComment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShiComment()
        {
            this.ShiReply = new HashSet<ShiReply>();
        }
    
        public int ShiComment_id { get; set; }
        public int Shi_id { get; set; }
        public string ComContent { get; set; }
        public System.DateTime ComTime { get; set; }
        public string Users_id { get; set; }
    
        public virtual Shi Shi { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShiReply> ShiReply { get; set; }
    }
}
