//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDati
    {
        public int Dati_id { get; set; }
        public string Users_id { get; set; }
        public int Timu_id { get; set; }
    
        public virtual Challenge Challenge { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
