//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_AuthorShi
    {
        public int Author_id { get; set; }
        public string AuthorName { get; set; }
        public string AuthorImage { get; set; }
        public string Jieshao { get; set; }
        public int Shi_id { get; set; }
        public string ShiTitle { get; set; }
        public string ShiImage { get; set; }
    }
}
