//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_PostIndex
    {
        public int Post_id { get; set; }
        public string PostTitle { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string Users_id { get; set; }
        public int LunTan_id { get; set; }
        public string PostDetails { get; set; }
        public string PostImage { get; set; }
        public string PostJianjie { get; set; }
        public Nullable<int> Post_top { get; set; }
        public Nullable<int> Post_recommend { get; set; }
        public Nullable<int> Post_draft { get; set; }
        public Nullable<int> Post_down { get; set; }
        public Nullable<int> Post_upvote { get; set; }
        public Nullable<int> Post_click { get; set; }
        public Nullable<int> Shi_id { get; set; }
        public Nullable<int> Ci_id { get; set; }
        public string Mp3_Url { get; set; }
        public string Expr1 { get; set; }
        public string UserName { get; set; }
        public string UserImage { get; set; }
        public string UserSign { get; set; }
        public string Post_upvoteId { get; set; }
        public string Post_downId { get; set; }
    }
}
