//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_UserInfo
    {
        public int Guanzhu_id { get; set; }
        public string UserA { get; set; }
        public string UserB { get; set; }
        public string UserName { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> Addtime { get; set; }
        public string UserSign { get; set; }
        public string UserImage { get; set; }
        public string Address { get; set; }
        public Nullable<int> Jifen { get; set; }
        public string UserName2 { get; set; }
        public string UserPhone { get; set; }
        public string UserPhone2 { get; set; }
        public string UserMail { get; set; }
        public string UserMail2 { get; set; }
        public string Sex2 { get; set; }
        public Nullable<System.DateTime> Addtime2 { get; set; }
        public string UserSign2 { get; set; }
        public string UserImage2 { get; set; }
        public string Address2 { get; set; }
        public Nullable<int> Jifen2 { get; set; }
        public Nullable<int> Jingyan { get; set; }
        public Nullable<int> Jingyan2 { get; set; }
    }
}
