//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_CiReply
    {
        public int Reply_id1 { get; set; }
        public string ReplyContent1 { get; set; }
        public Nullable<System.DateTime> ReplyTime1 { get; set; }
        public Nullable<int> ReReply_id1 { get; set; }
        public Nullable<int> Ci_id1 { get; set; }
        public string Users_id1 { get; set; }
        public string UserName1 { get; set; }
        public string UserImage1 { get; set; }
        public string Users_id2 { get; set; }
        public string UserName2 { get; set; }
        public string UserImage2 { get; set; }
        public Nullable<int> Reply_id2 { get; set; }
        public string ReplyContent2 { get; set; }
        public Nullable<System.DateTime> ReplyTime2 { get; set; }
        public Nullable<int> ReReply_id2 { get; set; }
        public Nullable<int> Ci_id2 { get; set; }
    }
}
