//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_CiShow
    {
        public int CiPai_id { get; set; }
        public string CiPaiName { get; set; }
        public string CiPaiImage { get; set; }
        public int Ci_id { get; set; }
        public string CiTitle { get; set; }
        public Nullable<int> Author_id { get; set; }
        public string AuthorName { get; set; }
    }
}
