//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Search
    {
        public int Author_id { get; set; }
        public string AuthorName { get; set; }
        public string AuthorImage { get; set; }
        public string Jieshao { get; set; }
        public int Ci_id { get; set; }
        public string CiTitle { get; set; }
        public string CiContent { get; set; }
        public string CiImage { get; set; }
        public int Goods_id { get; set; }
        public string GoodsName { get; set; }
        public string GoodsImage { get; set; }
        public string GoodsJianjie { get; set; }
        public int Post_id { get; set; }
        public string PostTitle { get; set; }
        public int LunTan_id { get; set; }
        public string PostDetails { get; set; }
        public string PostJianjie { get; set; }
        public int Shi_id { get; set; }
        public string ShiTitle { get; set; }
        public string ShiContent { get; set; }
        public string ShiImage { get; set; }
        public int Time_id { get; set; }
        public string TimeName { get; set; }
        public string TimeJieshao { get; set; }
        public string TimeImage { get; set; }
        public string Users_id { get; set; }
        public string UserName { get; set; }
        public string UserImage { get; set; }
        public string UserSign { get; set; }
        public int Video_id { get; set; }
        public string VideoName { get; set; }
        public string Cover { get; set; }
    }
}
